name: Fly Deploy
on:
  push:
  schedule:
    - cron: '30 20 * * *'


env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo '${{ secrets.CONFIG }}' > ./config.yaml

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only

